---

### ğŸ Kodlama SerÃ¼venim

<p align="center">
  <picture>
    <source media="(prefers-color-scheme: dark)" srcset="https://raw.githubusercontent.com/berkaycelik1/berkaycelik1/output/github-contribution-grid-snake-dark.svg">
    <source media="(prefers-color-scheme: light)" srcset="https://raw.githubusercontent.com/berkaycelik1/berkaycelik1/output/github-contribution-grid-snake.svg">
    <img alt="github contribution grid snake animation" src="https://raw.githubusercontent.com/berkaycelik1/berkaycelik1/output/github-contribution-grid-snake.svg">
  </picture>
</p>
